### ISSUE TITLE
Infografía

### ISSUE THREAD

**Issue by MarcosJonathan17** [SistemasTecTlaxiaco/infografia-MarcosJonathan17-1#2]
![conceptos y fases de gestión de proyectos de software](https://user-images.githubusercontent.com/80285829/133013158-a43b6dae-bcfc-45b4-9d78-33f245a3d28d.png)

**Comment by JulioCesar69** [comment]
Las imágenes no tienen relación con el tema, no contiene referencias bibliográficas. 
Calificación:  14.29

**Comment by josealfredo79** [comment]
Falta las metodologías, herramientas. bien hecho y revisado
